# Neural Network Walkthrough
---
## Manually Compute Neural Networks by hand
---

## Import Libraries

In [15]:
import numpy as np #to perform matrix multiplications and array operations
import matplotlib.pyplot as plt

## Implementation

In [19]:
class NeuralNet(object):
	"""
	A Neural Network Walkthrough
	"""
	def __init__(self, input_layer=4, hidden_layer=3, output_layer=1):
		"""Design and Initialise the Neural Network 
        input_layer= The number of feature you need to train for
        hidden_layer= the number of units in a hidden layer
        output_layer= the number of ouput units
        """
		np.random.seed(42)  #Seed is set so as to get the same random distribution every time the program is executed
		"""The following is used to initialize the weights and bias matrices with random values"""
		self.weightsh=np.random.uniform(size=(input_layer,hidden_layer)) 
		self.biash=np.random.uniform(size=(1,hidden_layer))
		self.weightsout=np.random.uniform(size=(hidden_layer,output_layer))
		self.biasout=np.random.uniform(size=(1,output_layer))


	def train(self, X, y, epochs = 10, lr = 1, verbose = True):
		"""Train the weigths of the neural network 
        epochs= the numbers of iteration the models should trained for
        lr =learning rate(alpha) for the model
        """

		# Begin Training
		for i in range(epochs):
			#Forward Propogation
			hidden_layer_input=np.dot(X,self.weightsh) + self.biash
			hiddenlayer_activations = self.sigmoid(hidden_layer_input)
			output_layer_input=np.dot(hiddenlayer_activations,self.weightsout) + self.biasout
			output = self.sigmoid(output_layer_input)

			#Backpropagation
			Error = y-output
			slope_output_layer = self.derivatives_sigmoid(output)
			slope_hidden_layer = self.derivatives_sigmoid(hiddenlayer_activations)
			delta_output = Error * slope_output_layer
			error_hidden_layer = delta_output.dot(self.weightsout.T)
			delta_hiddenlayer = error_hidden_layer * slope_hidden_layer
			self.weightsout += hiddenlayer_activations.T.dot(delta_output) *lr
			self.biasout += np.sum(delta_output, axis=0,keepdims=True) *lr
			self.weightsh += X.T.dot(delta_hiddenlayer) *lr
			self.biash += np.sum(delta_hiddenlayer, axis=0,keepdims=True) *lr

	def predict(self, X):
		"""Used to predict the value on the basis of the learned weights and bias"""
		hidden_layer_input=np.dot(X,self.weightsh) + self.biash
		hiddenlayer_activations = self.sigmoid(hidden_layer_input)
		output_layer_input=np.dot(hiddenlayer_activations,self.weightsout) + self.biasout
		output = self.sigmoid(output_layer_input)
		return output
	
	#Sigmoid Function
	def sigmoid (self,x):
		return 1/(1 + np.exp(-x))

	#Derivative of Sigmoid Function
	def derivatives_sigmoid(self,x):
		return x * (1 - x)


## Learning a Function

In [20]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

In [21]:
y=np.array([[1],[1],[0]])

In [22]:
MyNeuralNet1 = NeuralNet() #using default parameters input_layer=4, hidden_layer=3, output_layer=1

In [23]:
MyNeuralNet1.train(X, y, epochs=10, lr=10)

In [24]:
MyNeuralNet1.predict(X)

array([[ 0.9530459 ],
       [ 0.94823684],
       [ 0.81200963]])

## Learning XOR

In [51]:
X1 = np.array([[0,0],
               [0,1],
               [1,0],
               [1,1]])

y1 = np.array([[0],[1],[1],[0]])

In [52]:
MyNeuralNet2 = NeuralNet(input_layer=2, hidden_layer=4, output_layer=1)

In [63]:
MyNeuralNet2.train(X1, y1, epochs=100, lr=1)

In [64]:
predictions = MyNeuralNet2.predict(X1)#storing the predicted values in a variable
predictions

array([[ 0.03596955],
       [ 0.9332112 ],
       [ 0.93592023],
       [ 0.09513244]])

## Learning concentric circles

#### $$The\ circle\ with\ radius\ less\ than\ \sqrt{2}\ are\ 0,\ 1\ otherwise$$ 

In [46]:
X1=np.array([[1,1],
             [-1,1],
             [1,2],
             [-1,-1],
             [2,1],
             [1,-1],
             [2,2],
             [-2,1],
             [-2,-2],
             [1,-2]])
y1=np.array([[0],[0],[1],[0],[1],[0],[1],[1],[1],[1]])

In [47]:
MyNeuralNet3=NeuralNet(input_layer=2, hidden_layer=4, output_layer=1)

In [48]:
MyNeuralNet3.train(X1, y1, epochs=1000, lr=1)

In [66]:
predictions = nn.predict(X1)
predictions


array([[ 0.00030057],
       [ 0.00286672],
       [ 0.00598863],
       [ 0.03788425]])

In [50]:
np.around(predictions) 

array([[ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])